name: cwc_package
description: "Course Walk Companion package"
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: 0.17.0
  permission_handler: ^10.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.3
  camera:
  shared_preferences: ^2.0.15
#  package_info_plus: ^8.0.2
  package_info_plus: ^5.0.1

  latlong2: ^0.9.0
#   flutter_compass: ^0.8.0
#  flutter_map: ^7.0.2
  flutter_map: ^6.1.0

  flutter_map_location_marker: any
  google_mobile_ads: ^5.1.0

  http_parser:
  http: ^1.1.2
  uuid: ^4.2.1
# connectivity_plus: ^6.0.5
  connectivity_plus: ^5.0.2


  gps_tracker:
    path: /Users/macbook/StudioProjects/gps_tracker
  gps_tracker_db:
    path: /Users/macbook/StudioProjects/gps_tracker_db

flutter:
  assets:
    - lib/assets/images/

